### ISSUE TITLE
Admin-configurable disallow direct blueprints in certain channels

### ISSUE THREAD

**Issue by demodude4u** [demodude4u/Factorio-FBSR#104]
Fail to work with direct blueprint strings contained within discord messages, when specified by the admin where it should not work (particularly in busy channels that don't like walls of blueprint string)

**Comment by demodude4u** [comment]
Alternatively, this could be done in another way, where the bot will delete the message containing the direct blueprint string, and replace it with an uploaded text url.  This feature could automatically work based on the permissions given.

**Comment by Bilka2** [comment]
This is was solved by switching to slash commands. The command display on Discord's side doesn't show the full string until the users clicks on the used command. The bp string is still available via the link at the top of the message.
