### ISSUE TITLE
Rail Station Names

### ISSUE THREAD

**Issue by demodude4u** [demodude4u/Factorio-FBSR#107]

**Comment by Bilka2** [comment]
Currently rail station names are not actually exported to the blueprint string (bug?). The string from a blueprint with remembered names is the same as for one with the same setup without remembered names.

**Comment by Bilka2** [comment]
Lmao nevermind, that was just fixed, so it'll save the names in 0.16.7+.

**Comment by FactorioBlueprints** [comment]
Oh wow, that is awesome. I should display them too. Thanks!
