### ISSUE TITLE
phantom speed modules

### ISSUE THREAD

**Issue by maerlyn** [demodude4u/Factorio-FBSR#112]
Here's the generated image: https://cdn.discordapp.com/attachments/334735604342325249/429940901578539008/blueprint.png
Here's the blueprint book: https://pastebin.com/zBTXsucW
And here's the reddit thread: https://www.reddit.com/r/factorio/comments/88o04d/train_cells_for_science_etc_feedback_appreciated/dwmdbqj/

Have a look at any of the assembly machines makind red potions, they have quite a few speed modules displayed at their top edge.

**Comment by acid1103** [comment]
That's displaying the modules that the assembly machines are receiving from the beacons. I'm not certain, but I believe that's intended.

**Comment by maerlyn** [comment]
Hmm, that seems logical (and checks out, counting the beacons that affect the assembly machine I checked).

**Comment by demodude4u** [comment]
@acid1103 is right, it's showing the effective additional modules from beacons.

**Comment by maerlyn** [comment]
Thanks for the info!
