### ISSUE TITLE
CamelCase typo breaking the bot on linux

### ISSUE THREAD

**Issue by tzwaan** [demodude4u/Factorio-FBSR#114]
When trying to load the dataloader.lua file, the blueprintbot uses the following as the path:

/factorio/data/core/lua**L**ib/dataloader.lua

On windows this works fine due to the fact that casing is ignored. On linux this results in an error.

The line should changed to:

/factorio/data/core/lua**l**ib/dataloader.lua

**Comment by acid1103** [comment]
This is technically an issue with [Java-Factorio-Data-Wrapper](https://github.com/demodude4u/Java-Factorio-Data-Wrapper). If you could move this issue over there, I have a commit ready to be pulled and merged. Thanks.

**Comment by demodude4u** [comment]
Moved issue, thanks for the commit @acid1103 !
