### ISSUE TITLE
Doesn't render wires for combinators that are connected to themselves

### ISSUE THREAD

**Issue by Bilka2** [demodude4u/Factorio-FBSR#118]

**Comment by sparr** [comment]
```0eNqVkttqwzAMht9F1+5oQtO0Zm8ySnBitRMkdvChLBS/+2R7jMJgbDfGkqVP0i8/YJwjro5MAPkAmqzxIN8e4Olm1Jx9YVsRJFDABQQYtWRL40Qa3W6yy0hGBesgCSCj8QNkky4C0AQKhJVWjG0wcRnRccBvHAGr9ZxqTa7OuF1z7gRs+XLqXzquo8nhVCNaAdxzcHYeRnxXd2ICp31xB37TheWz90rOh+HHaHdyIbLnu6sascM7ui28k7nl4bI0QWWdmq7d77NjWZUrPUt45Wwbwxr/wb85RFPR68atRhOGq7PLQIY5IK9q9phqaVMHLmM0+XCon6UlXWSdyE2RQjHbdOHc9m/BvLOU8t7KnuXTtxDAMvgq9qk59Idzf+yb/bE7pvQJqj3ETg==```
A single combinator connected to itself with a red wire for testing purposes.

**Comment by demodude4u** [comment]
Thanks @Fl0GUI !
