### ISSUE TITLE
Image hosting problem

### ISSUE THREAD

**Issue by rickyzhangca** [demodude4u/Factorio-FBSR#145]
@demodude4u Hi Demod! I'm the creator of [fprints.xyz](http://fprints.xyz/). I have been studying FBSR's 2.0 branch to see if I could integrate it. I saw we are looking for an image hosting solution to replace Discord's. I'm happy to see if I can help with some bandwidth in my buckets and CDN. Maybe we can do a collab! Let's chat?

I couldn't find you via "demodude4u" on discord. I wondering what's the best way to reach out to you? (or any other apps you prefer)

**Comment by rickyzhangca** [comment]
Gonna chat on discord!

**Comment by FactorioBlueprints** [comment]
Hi @rickyzhangca I'm the author of factorioprints and factorio.school. I've been working (quietly) on an uplift for 2.0 and I'd love to collaborate rather than compete. Could we chat on discord? You can find me at https://factorioprints.com/chat
